services:
  samba:
    image: dockurr/samba
    container_name: samba
    environment:
      NAME: "data"
      USER: "smb"
      PASS: "password"
    ports:
      - 445:445
    volumes:
      - ./samba:/storage
    restart: always
